import { Agent, Property } from './types';

const img = (id: string, n: number) => `https://picsum.photos/seed/aq-${id}-${n}/900/620`;

const AGENTS: Agent[] = [
  { name: 'مهندس أحمد حسن', phone: '01001234567', company: 'الأفق للعقارات', rating: 4.8, deals: 132 },
  { name: 'سارة محمود', phone: '01112345678', company: 'دار المعمار', rating: 4.9, deals: 98 },
  { name: 'كريم عادل', phone: '01012345678', company: 'بيت العقار', rating: 4.7, deals: 210 },
  { name: 'منى السيد', phone: '01223456789', company: 'أفق التجمع', rating: 4.8, deals: 76 },
];

export const PROPERTIES: Property[] = [
  {
    id: 'aq01',
    title: 'شقة 115 م² تشطيب سوبر لوكس في كمبوند أزهرة',
    type: 'apartment',
    purpose: 'sale',
    price: 3600000,
    city: 'القاهرة الجديدة',
    compound: 'كمبوند أزهرة',
    area: 115,
    rooms: 3,
    bathrooms: 2,
    floor: 7,
    amenities: ['parking', 'pool', 'security', 'kids', 'mall'],
    images: [img('aq01', 1), img('aq01', 2), img('aq01', 3)],
    description:
      'شقة مميزة بمساحة 115 م² في قلب كمبوند أزهرة بالقاهرة الجديدة، تشطيب سوبر لوكس بإطلالة على حمام السباحة. تصلح للسكن الفوري أو كاستثمار مضمون في مناطق الطلب الأعلى.',
    features: ['إطلالة على حمام السباحة', 'أفضل واجهة في البناية', 'قريب من الجامعة الأمريكية', 'كمبوند متكامل الخدمات'],
    finishing: 'تشطيب سوبر لوكس',
    paymentPlan: 'مقدم 10% وتقسيط على 7 سنوات',
    delivery: 'ready',
    status: 'مميز',
    agent: AGENTS[0],
    yearBuilt: 2023,
  },
  {
    id: 'aq02',
    title: 'شقة 140 م² بحديقة خاصة في كمبوند ميفيدا',
    type: 'apartment',
    purpose: 'sale',
    price: 5200000,
    city: 'التجمع الخامس',
    compound: 'كمبوند ميفيدا',
    area: 140,
    rooms: 3,
    bathrooms: 3,
    floor: 12,
    amenities: ['garden', 'pool', 'gym', 'security', 'parking', 'view'],
    images: [img('aq02', 1), img('aq02', 2), img('aq02', 3)],
    description:
      'شقة فاخرة بمساحة 140 م² في التجمع الخامس، تشطيب كامل مع حديقة خاصة على مساحة 30 م². تقع في أعلى طوابق البناية بإطلالة بانورامية على الخدمات الخضراء للكمبوند.',
    features: ['حديقة خاصة 30 م²', 'إطلالة بانورامية', 'أعلى طوابق البناية', 'تشطيب كامل جاهز للسكن'],
    finishing: 'تشطيب كامل',
    paymentPlan: 'مقدم 15% وتقسيط على 8 سنوات',
    delivery: 'ready',
    status: 'جديد',
    agent: AGENTS[1],
    yearBuilt: 2024,
  },
  {
    id: 'aq03',
    title: 'شقة 95 م² نصف تشطيب في حي الزهراء',
    type: 'apartment',
    purpose: 'sale',
    price: 2400000,
    city: 'مدينة نصر',
    area: 95,
    rooms: 2,
    bathrooms: 2,
    floor: 4,
    amenities: ['elevator', 'parking', 'security'],
    images: [img('aq03', 1), img('aq03', 2), img('aq03', 3)],
    description:
      'فرصة استثمارية ممتازة في حي الزهراء بمدينة نصر، شقة 95 م² بنصف تشطيب تتيح لك اختيار تشطيبك بنفسك. موقع حيوي قريب من كل الخدمات والمحاور الرئيسية.',
    features: ['موقع حيوي قريب من النزل الأمريكي', 'مصعد ومواقف خاصة', 'إطلالة مفتوحة', 'سعر منافس للمنطقة'],
    finishing: 'نصف تشطيب',
    delivery: 'ready',
    status: null,
    agent: AGENTS[2],
    yearBuilt: 2015,
  },
  {
    id: 'aq04',
    title: 'شقة 160 م² سوبر لوكس في كمبوند سوان ليك',
    type: 'apartment',
    purpose: 'sale',
    price: 7800000,
    city: 'الشيخ زايد',
    compound: 'كمبوند سوان ليك',
    area: 160,
    rooms: 3,
    bathrooms: 3,
    floor: 18,
    amenities: ['pool', 'gym', 'security', 'parking', 'garden', 'mall'],
    images: [img('aq04', 1), img('aq04', 2), img('aq04', 3)],
    description:
      'شقة فاخرة بمساحة 160 م² في كمبوند سوان ليك بالشيخ زايد، تشطيب سوبر لوكس في الدور الثامن عشر. الكمبوند يضم أكبر بحيرة صناعية في المنطقة ومساحات خضراء شاسعة.',
    features: ['إطلالة على البحيرة الصناعية', 'دور عالي وإطلالة مفتوحة', 'كمبوند عالمي المستوى', 'قريب من مول العرب'],
    finishing: 'تشطيب سوبر لوكس',
    paymentPlan: 'مقدم 20% وتقسيط على 6 سنوات',
    delivery: 'ready',
    status: 'مميز',
    agent: AGENTS[0],
    yearBuilt: 2022,
  },
  {
    id: 'aq05',
    title: 'شقة 130 م² تشطيب كامل في كمبوند ألالا',
    type: 'apartment',
    purpose: 'sale',
    price: 6500000,
    city: 'المعادي',
    compound: 'كمبوند ألالا',
    area: 130,
    rooms: 3,
    bathrooms: 2,
    floor: 9,
    amenities: ['security', 'parking', 'pool', 'kids'],
    images: [img('aq05', 1), img('aq05', 2), img('aq05', 3)],
    description:
      'شقة عائلية بمساحة 130 م² في كمبوند ألالا بالمعادي، تشطيب كامل جاهز للسكن الفوري. الكمبوند هادئ وآمن ويناسب العائلات، مع خدمات ترفيهية متكاملة.',
    features: ['مناسب للعائلات', 'أمن وحراسة على مدار الساعة', 'قريب من المدارس الدولية', 'خدمات ترفيهية متكاملة'],
    finishing: 'تشطيب كامل',
    paymentPlan: 'مقدم 15% وتقسيط على 7 سنوات',
    delivery: 'ready',
    status: null,
    agent: AGENTS[1],
    yearBuilt: 2021,
  },
  {
    id: 'aq06',
    title: 'شقة 85 م² في أبراج العاصمة الإدارية',
    type: 'apartment',
    purpose: 'sale',
    price: 3100000,
    city: 'العاصمة الإدارية الجديدة',
    compound: 'أبراج العاصمة',
    area: 85,
    rooms: 2,
    bathrooms: 2,
    floor: 22,
    amenities: ['pool', 'security', 'gym', 'parking', 'mall', 'view'],
    images: [img('aq06', 1), img('aq06', 2), img('aq06', 3)],
    description:
      'شقة استثمارية بمساحة 85 م² في قلب العاصمة الإدارية الجديدة، الدور الثاني والعشرون بإطلالة على الأبراج. عائد تأجيري مضمون في أسرع المناطق نموًا.',
    features: ['عائد تأجيري مضمون', 'إطلالة على الأبراج', 'تشطيب كامل جاهز فورًا', 'أعلى عائد استثماري في المنطقة'],
    finishing: 'تشطيب كامل',
    paymentPlan: 'مقدم 10% وتقسيط على 8 سنوات',
    delivery: 'ready',
    status: 'جديد',
    agent: AGENTS[3],
    yearBuilt: 2024,
  },
  {
    id: 'aq07',
    title: 'شقة 200 م² بتراس خاص في الزمالك',
    type: 'apartment',
    purpose: 'sale',
    price: 18000000,
    city: 'الزمالك',
    area: 200,
    rooms: 4,
    bathrooms: 3,
    floor: 1,
    amenities: ['elevator', 'parking', 'security', 'view', 'storage'],
    images: [img('aq07', 1), img('aq07', 2), img('aq07', 3)],
    description:
      'شقة نادرة بمساحة 200 م² في الزمالك مع تراس خاص على النيل. تشطيب سوبر لوكس، دور أرضي بمدخل مستقل، فرصة لا تتكرر في من أرقى أحياء القاهرة.',
    features: ['تراس خاص على النيل', 'مدخل مستقل', 'دور أرضي بحديقة', 'فرصة استثمارية نادرة'],
    finishing: 'تشطيب سوبر لوكس',
    delivery: 'ready',
    status: 'عاجل',
    agent: AGENTS[2],
    yearBuilt: 2010,
  },
  {
    id: 'aq08',
    title: 'شقة 105 م² تشطيب كامل في كمبوند بوديا',
    type: 'apartment',
    purpose: 'sale',
    price: 3900000,
    city: 'مدينة السادس من أكتوبر',
    compound: 'كمبوند بوديا',
    area: 105,
    rooms: 3,
    bathrooms: 2,
    floor: 5,
    amenities: ['pool', 'security', 'kids', 'parking', 'gym'],
    images: [img('aq08', 1), img('aq08', 2), img('aq08', 3)],
    description:
      'شقة بمساحة 105 م² في كمبوند بوديا بالسادس من أكتوبر، تشطيب كامل بتصميمات عصرية. الكمبوند يوفر حياة هادئة بمساحات خضراء كبيرة وخدمات متكاملة.',
    features: ['تصميمات عصرية', 'قريب من محور 26 يوليو', 'مساحات خضراء واسعة', 'سعر مناسب للمقارنة'],
    finishing: 'تشطيب كامل',
    paymentPlan: 'مقدم 12% وتقسيط على 7 سنوات',
    delivery: 'ready',
    status: null,
    agent: AGENTS[0],
    yearBuilt: 2023,
  },
  {
    id: 'aq09',
    title: 'فيلا 280 م² بمسبح خاص في كمبوند نيو جيزة',
    type: 'villa',
    purpose: 'sale',
    price: 16500000,
    city: 'الشيخ زايد',
    compound: 'كمبوند نيو جيزة',
    area: 280,
    rooms: 4,
    bathrooms: 4,
    amenities: ['garden', 'pool', 'security', 'parking', 'smartHome', 'concierge'],
    images: [img('aq09', 1), img('aq09', 2), img('aq09', 3)],
    description:
      'فيلا توين هاوس بمساحة 280 م² في كمبوند نيو جيزة، بمسبح خاص وحديقة 60 م². تشطيب سوبر لوكس بنظام المنزل الذكي، جاهزة للسكن الفوري.',
    features: ['مسبح خاص', 'حديقة 60 م²', 'نظام منزل ذكي', 'كونسيرج 24 ساعة'],
    finishing: 'تشطيب سوبر لوكس',
    paymentPlan: 'مقدم 20% وتقسيط على 6 سنوات',
    delivery: 'ready',
    status: 'مميز',
    agent: AGENTS[1],
    yearBuilt: 2022,
  },
  {
    id: 'aq10',
    title: 'توين هاوس 210 م² في كمبوند أزهرة',
    type: 'townhouse',
    purpose: 'sale',
    price: 11800000,
    city: 'التجمع الخامس',
    compound: 'كمبوند أزهرة',
    area: 210,
    rooms: 3,
    bathrooms: 3,
    amenities: ['garden', 'parking', 'security', 'kids'],
    images: [img('aq10', 1), img('aq10', 2), img('aq10', 3)],
    description:
      'توين هاوس بمساحة 210 م² في التجمع الخامس، بحديقة خاصة ومدخل مستقل. تشطيب كامل بتصميمات عصرية تناسب العائلات التي تبحث عن الخصوصية والهدوء.',
    features: ['حديقة خاصة', 'مدخل مستقل', 'خصوصية تامة', 'تصميمات عصرية'],
    finishing: 'تشطيب كامل',
    paymentPlan: 'مقدم 15% وتقسيط على 8 سنوات',
    delivery: 'ready',
    status: null,
    agent: AGENTS[3],
    yearBuilt: 2023,
  },
  {
    id: 'aq11',
    title: 'فيلا 350 م² على البحر في سيدي عبد الرحمن',
    type: 'villa',
    purpose: 'sale',
    price: 28000000,
    city: 'الساحل الشمالي',
    compound: 'سيدي عبد الرحمن',
    area: 350,
    rooms: 5,
    bathrooms: 4,
    amenities: ['view', 'pool', 'garden', 'security', 'parking', 'smartHome', 'tennis'],
    images: [img('aq11', 1), img('aq11', 2), img('aq11', 3)],
    description:
      'فيلا ساحلية فاخرة بمساحة 350 م² على بعد أمتار من البحر في سيدي عبد الرحمن. إطلالة بانورامية على البحر المتوسط، مسبح خاص، وتشطيب سوبر لوكس بمعايير عالمية.',
    features: ['على بعد أمتار من البحر', 'إطلالة بانورامية', 'مسبح خاص', 'ملعب تنس'],
    finishing: 'تشطيب سوبر لوكس',
    paymentPlan: 'مقدم 25% وتقسيط على 5 سنوات',
    delivery: 'ready',
    status: 'مميز',
    agent: AGENTS[2],
    yearBuilt: 2023,
  },
  {
    id: 'aq12',
    title: 'تاون هاوس 190 م² في ذا كابيتال هايتس',
    type: 'townhouse',
    purpose: 'sale',
    price: 13500000,
    city: 'العاصمة الإدارية الجديدة',
    compound: 'ذا كابيتال هايتس',
    area: 190,
    rooms: 3,
    bathrooms: 3,
    amenities: ['garden', 'parking', 'security', 'mall', 'gym', 'clubhouse'],
    images: [img('aq12', 1), img('aq12', 2), img('aq12', 3)],
    description:
      'تاون هاوس بمساحة 190 م² في قلب العاصمة الإدارية الجديدة، بحديقة خاصة ونادي اجتماعي. موقع استراتيجي قريب من الحي الحكومي والمسجد الأكبر.',
    features: ['حديقة خاصة', 'نادي اجتماعي', 'قريب من الحي الحكومي', 'خدمات متكاملة'],
    finishing: 'تشطيب كامل',
    paymentPlan: 'مقدم 10% وتقسيط على 10 سنوات',
    delivery: 'ready',
    status: 'جديد',
    agent: AGENTS[3],
    yearBuilt: 2024,
  },
  {
    id: 'aq13',
    title: 'فيلا 240 م² بإطلالة بحرية في العين السخنة',
    type: 'villa',
    purpose: 'sale',
    price: 14200000,
    city: 'العين السخنة',
    compound: 'كمبوند أمواج',
    area: 240,
    rooms: 4,
    bathrooms: 3,
    amenities: ['view', 'pool', 'security', 'parking', 'garden'],
    images: [img('aq13', 1), img('aq13', 2), img('aq13', 3)],
    description:
      'فيلا بمساحة 240 م² في كمبوند أمواج بالعين السخنة، بإطلالة مباشرة على البحر الأحمر. مسبح خاص وحديقة، جاهزة للاستلام الفوري.',
    features: ['إطلالة مباشرة على البحر', 'مسبح خاص', 'جاهزة للاستلام الفوري', 'شاطئ خاص للكمبوند'],
    finishing: 'تشطيب سوبر لوكس',
    paymentPlan: 'مقدم 20% وتقسيط على 7 سنوات',
    delivery: 'ready',
    status: null,
    agent: AGENTS[1],
    yearBuilt: 2023,
  },
  {
    id: 'aq14',
    title: 'شقة 120 م² مفروشة للإيجار في المعادي',
    type: 'apartment',
    purpose: 'rent',
    price: 8500,
    city: 'المعادي',
    area: 120,
    rooms: 3,
    bathrooms: 2,
    floor: 6,
    amenities: ['elevator', 'security', 'parking', 'ac', 'furnished'],
    images: [img('aq14', 1), img('aq14', 2), img('aq14', 3)],
    description:
      'شقة مفروشة للإيجار بمساحة 120 م² في المعادي، 3 غرف وصالتين. تكييف مركزي، مصعد، ومواقف سيارة. جاهزة للسكن الفوري للعائلات.',
    features: ['مفروشة بالكامل', 'تكييف مركزي', 'جاهزة للسكن الفوري', 'منطقة هادئة'],
    finishing: 'مفروش',
    delivery: 'ready',
    status: null,
    agent: AGENTS[0],
    yearBuilt: 2018,
  },
  {
    id: 'aq15',
    title: 'شقة 150 م² للإيجار في مدينة نصر',
    type: 'apartment',
    purpose: 'rent',
    price: 12000,
    city: 'مدينة نصر',
    area: 150,
    rooms: 3,
    bathrooms: 2,
    floor: 8,
    amenities: ['elevator', 'security', 'kids'],
    images: [img('aq15', 1), img('aq15', 2), img('aq15', 3)],
    description:
      'شقة واسعة بمساحة 150 م² للإيجار في مدينة نصر، 3 غرف نوم كبيرة وصالتين. تشطيب كامل في دور عالي بإطلالة مفتوحة، قريبة من كل الخدمات.',
    features: ['دور عالي بإطلالة مفتوحة', 'قريبة من المحاور الرئيسية', 'تشطيب كامل', 'منطقة خدمات متكاملة'],
    finishing: 'تشطيب كامل',
    delivery: 'ready',
    status: null,
    agent: AGENTS[2],
    yearBuilt: 2016,
  },
  {
    id: 'aq16',
    title: 'شقة 90 م² مفروشة للإيجار في سموحة',
    type: 'apartment',
    purpose: 'rent',
    price: 4500,
    city: 'الإسكندرية',
    compound: 'سموحة',
    area: 90,
    rooms: 2,
    bathrooms: 1,
    floor: 3,
    amenities: ['elevator', 'ac', 'furnished'],
    images: [img('aq16', 1), img('aq16', 2), img('aq16', 3)],
    description:
      'شقة مفروشة بمساحة 90 م² في سموحة بالإسكندرية، غرفتي نوم وصالة. تكييف سبليت في كل الغرف، مفروشة بمستوى عالي، جاهزة للسكن الفوري.',
    features: ['مفروشة بمستوى عالي', 'تكييف سبليت', 'قريبة من البحر', 'منطقة حيوية'],
    finishing: 'مفروش',
    delivery: 'ready',
    status: null,
    agent: AGENTS[1],
    yearBuilt: 2019,
  },
  {
    id: 'aq17',
    title: 'فيلا 300 م² مفروشة للإيجار في الشيخ زايد',
    type: 'villa',
    purpose: 'rent',
    price: 45000,
    city: 'الشيخ زايد',
    area: 300,
    rooms: 5,
    bathrooms: 4,
    amenities: ['pool', 'garden', 'security', 'parking', 'smartHome', 'furnished'],
    images: [img('aq17', 1), img('aq17', 2), img('aq17', 3)],
    description:
      'فيلا فاخرة بمساحة 300 م² للإيجار في الشيخ زايد، مفروشة بالكامل بمستوى عالي. مسبح خاص وحديقة 80 م²، نظام منزل ذكي وحراسة 24 ساعة.',
    features: ['مفروشة بالكامل', 'مسبح خاص', 'حديقة 80 م²', 'نظام منزل ذكي'],
    finishing: 'مفروش',
    delivery: 'ready',
    status: 'عاجل',
    agent: AGENTS[0],
    yearBuilt: 2021,
  },
  {
    id: 'aq18',
    title: 'شقة 110 م² للإيجار في العاصمة الإدارية',
    type: 'apartment',
    purpose: 'rent',
    price: 7000,
    city: 'العاصمة الإدارية الجديدة',
    area: 110,
    rooms: 2,
    bathrooms: 2,
    floor: 14,
    amenities: ['pool', 'security', 'gym', 'parking', 'ac'],
    images: [img('aq18', 1), img('aq18', 2), img('aq18', 3)],
    description:
      'شقة بمساحة 110 م² للإيجار في العاصمة الإدارية الجديدة، الدور الرابع عشر بإطلالة على المدينة. تشطيب كامل مع تكييف مركزي وخدمات الكمبوند المتكاملة.',
    features: ['إطلالة على المدينة', 'تكييف مركزي', 'خدمات كمبوند متكاملة', 'دور عالي'],
    finishing: 'تشطيب كامل',
    delivery: 'ready',
    status: null,
    agent: AGENTS[3],
    yearBuilt: 2023,
  },
  {
    id: 'aq19',
    title: 'أرض 400 م² في قلب العاصمة الإدارية',
    type: 'land',
    purpose: 'sale',
    price: 9500000,
    city: 'العاصمة الإدارية الجديدة',
    area: 400,
    rooms: 0,
    bathrooms: 0,
    amenities: [],
    images: [img('aq19', 1), img('aq19', 2), img('aq19', 3)],
    description:
      'أرض سكنية بمساحة 400 م² في قلب العاصمة الإدارية الجديدة، على الشارع الرئيسي بواجهة 20 متر. فرصة استثمارية نادرة في أسرع المناطق نموًا.',
    features: ['واجهة 20 متر على الشارع الرئيسي', 'أرض مرخصة سكني', 'فرصة استثمارية نادرة', 'قريبة من الحي الحكومي'],
    finishing: 'أرض خام',
    delivery: 'under-construction',
    status: null,
    agent: AGENTS[2],
  },
  {
    id: 'aq20',
    title: 'أرض 250 م² على البحر مباشرة في العين السخنة',
    type: 'land',
    purpose: 'sale',
    price: 6800000,
    city: 'العين السخنة',
    area: 250,
    rooms: 0,
    bathrooms: 0,
    amenities: ['view'],
    images: [img('aq20', 1), img('aq20', 2), img('aq20', 3)],
    description:
      'أرض بمساحة 250 م² في العين السخنة على البحر مباشرة، بإطلالة بحرية مفتوحة. مرخصة للبناء السكني والاستثماري، فرصة نادرة بهذا القرب من الشاطئ.',
    features: ['على البحر مباشرة', 'إطلالة بحرية مفتوحة', 'مرخصة للبناء', 'أعلى عائد استثماري'],
    finishing: 'أرض خام',
    delivery: 'ready',
    status: null,
    agent: AGENTS[1],
  },
  {
    id: 'aq21',
    title: 'أرض 600 م² في السادس من أكتوبر',
    type: 'land',
    purpose: 'sale',
    price: 7200000,
    city: 'مدينة السادس من أكتوبر',
    area: 600,
    rooms: 0,
    bathrooms: 0,
    amenities: [],
    images: [img('aq21', 1), img('aq21', 2), img('aq21', 3)],
    description:
      'أرض سكنية بمساحة 600 م² في السادس من أكتوبر، بواجهة 25 متر على شارع رئيسي. مناسبة لبناء فيلا أو عمارة سكنية، بالتقسيط المريح.',
    features: ['واجهة 25 متر', 'مناسبة لفيلا أو عمارة', 'تقسيط مريح', 'منطقة هادئة وراقية'],
    finishing: 'أرض خام',
    paymentPlan: 'مقدم 30% وتقسيط على 5 سنوات',
    delivery: 'ready',
    status: null,
    agent: AGENTS[0],
  },
  {
    id: 'aq22',
    title: 'محل تجاري 80 م² في الجولدن بلازا',
    type: 'commercial',
    purpose: 'sale',
    price: 5500000,
    city: 'القاهرة الجديدة',
    compound: 'الجولدن بلازا',
    area: 80,
    rooms: 0,
    bathrooms: 1,
    floor: 0,
    amenities: ['mall', 'security', 'parking', 'elevator'],
    images: [img('aq22', 1), img('aq22', 2), img('aq22', 3)],
    description:
      'محل تجاري بمساحة 80 م² في الجولدن بلازا بالقاهرة الجديدة، في الواجهة الرئيسية مباشرة. عائد تأجيري مضمون بأعلى أسعار المنطقة التجارية.',
    features: ['واجهة رئيسية مباشرة', 'عائد تأجيري مضمون', 'مواقف سيارات خاصة', 'أعلى كثافة مرورية'],
    finishing: 'محل تجاري',
    paymentPlan: 'مقدم 20% وتقسيط على 6 سنوات',
    delivery: 'ready',
    status: 'جديد',
    agent: AGENTS[2],
  },
  {
    id: 'aq23',
    title: 'مكتب إداري 120 م² في ذا كابيتال هايتس',
    type: 'office',
    purpose: 'sale',
    price: 4200000,
    city: 'العاصمة الإدارية الجديدة',
    compound: 'ذا كابيتال هايتس',
    area: 120,
    rooms: 2,
    bathrooms: 2,
    floor: 10,
    amenities: ['mall', 'security', 'parking', 'elevator', 'ac'],
    images: [img('aq23', 1), img('aq23', 2), img('aq23', 3)],
    description:
      'مكتب إداري بمساحة 120 م² في ذا كابيتال هايتس بالعاصمة الإدارية، الدور العاشر بإطلالة على الحي الحكومي. تشطيب كامل جاهز للعمل الفوري.',
    features: ['إطلالة على الحي الحكومي', 'تشطيب كامل', 'مواقف خاصة', 'قريب من الوزارات'],
    finishing: 'تشطيب كامل',
    paymentPlan: 'مقدم 15% وتقسيط على 7 سنوات',
    delivery: 'ready',
    status: null,
    agent: AGENTS[3],
  },
];
